name: SpaceONE Review

on:
  pull_request:
    branches:
      - master
jobs:
  review:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Empty review
      run: |
        echo "Empty review ..."
